name: CI

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync

      - name: Run linting
        run: |
          uv run ruff check .
          uv run ruff format --check .

      - name: Check Python syntax
        run: uv run python -m py_compile src/**/*.py
